// Generated by CoffeeScript 1.7.1
(function() {
  var Transform, name, numValue, order, xyValue, _fn, _i, _len;

  order = ["translate", "scale", "rotate"];

  xyValue = (function() {
    function xyValue(x, y) {
      this.x = x;
      this.y = y;
      if (this.x == null) {
        this.x = 0;
      }
      if (this.y == null) {
        this.y = 0;
      }
    }

    xyValue.prototype.value = function(newValue) {
      switch (typeof newValue) {
        case 'number':
          this.x = newValue;
          return this.y = newValue;
        case 'object':
          this.x = newValue.x != null ? newValue.x : newValue.x = newValue.x;
          return this.y = newValue.y != null ? newValue.y : newValue.y = newValue.x;
        case 'undefined':
          return {
            x: this.x,
            y: this.y
          };
      }
    };

    xyValue.prototype.toString = function() {
      return this.x + "," + this.y;
    };

    return xyValue;

  })();

  numValue = (function() {
    function numValue(number) {
      this.number = number;
      if (this.number == null) {
        this.number = 0;
      }
    }

    numValue.prototype.value = function(newValue) {
      if (newValue === 'undefined') {
        return this.number;
      }
      if (this.number !== newValue) {
        return this.number = Math.round(newValue % 360 + (newValue >= 0 ? 0 : 360));
      }
    };

    numValue.prototype.toString = function() {
      return this.number;
    };

    return numValue;

  })();

  Transform = (function() {
    function Transform(order) {
      if (this.translate == null) {
        this.translate = new xyValue(0, 0);
      }
      if (this.scale == null) {
        this.scale = new xyValue(1, 1);
      }
      if (this.rotate == null) {
        this.rotate = new numValue;
      }
    }

    return Transform;

  })();

  Transform.prototype.toString = function() {
    return order.map(function(name) {
      return name + "(" + this[name].toString() + ")";
    }, this).join(" ");
  };

  _fn = function(name) {
    return d3.selection.prototype[name] = function(value) {
      var e, i, _fn1, _j, _len1, _ref;
      _ref = this[0];
      _fn1 = function(e) {
        if (e.__transform__ == null) {
          e.__transform__ = new Transform;
        }
        switch (typeof value) {
          case 'number':
            return e.__transform__[name].value(value);
          case 'function':
            return e.__transform__[name].value(value(e.__data__, i));
        }
      };
      for (i = _j = 0, _len1 = _ref.length; _j < _len1; i = ++_j) {
        e = _ref[i];
        _fn1(e);
      }
      return this;
    };
  };
  for (_i = 0, _len = order.length; _i < _len; _i++) {
    name = order[_i];
    _fn(name);
  }

  d3.selection.prototype.contort = function() {
    var e, _fn1, _j, _len1, _ref;
    _ref = this[0];
    _fn1 = function(e) {
      return e.__transform__ != null ? e.__transform__ : e.__transform__ = new Transform;
    };
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      e = _ref[_j];
      _fn1(e);
    }
    return this;
  };

  d3.selection.prototype.render = function() {
    var e, _fn1, _j, _len1, _ref;
    _ref = this[0];
    _fn1 = function(e) {
      if (e.__transform__ == null) {
        e.__transform__ = new Transform;
      }
      return d3.select(e).attr("transform", e.__transform__.toString());
    };
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      e = _ref[_j];
      _fn1(e);
    }
    return this;
  };

  d3.selection.prototype.animate = function(options) {
    var duration, e, ease, opacity, _fn1, _j, _len1, _ref;
    if (options == null) {
      options = {};
    }
    duration = options.duration != null ? options.duration : options.duration = 500;
    ease = options.ease != null ? options.ease : options.ease = "ease";
    opacity = options.opacity != null ? options.opacity : options.opacity = "1";
    _ref = this[0];
    _fn1 = function(e) {
      if (e.__transform__ == null) {
        e.__transform__ = new Transform;
      }
      return d3.select(e).transition().duration(duration).ease(d3.ease(ease)).attr({
        transform: e.__transform__.toString(),
        "opacity": opacity
      });
    };
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      e = _ref[_j];
      _fn1(e);
    }
    return this;
  };

}).call(this);

//# sourceMappingURL=d3-contort.map
